package com.example.temp.tour_add.country_choice

import android.content.Intent
import android.os.Bundle
import android.os.PersistableBundle
import android.util.Log
import android.widget.LinearLayout
import android.widget.Toast
import androidx.appcompat.app.AppCompatActivity
import androidx.core.widget.addTextChangedListener
import androidx.recyclerview.widget.LinearLayoutManager
import com.example.temp.databinding.ActivityCountryChoiceBinding
import com.example.temp.tour_add.country_choice.rv.CountryListDataClass
import com.example.temp.tour_add.country_choice.rv.CountryListRvAdapter
import com.example.temp.tour_add.date_choice.DateChoiceActivity
import java.util.*

class CountryChoiceActivity:AppCompatActivity() {
    private lateinit var binding: ActivityCountryChoiceBinding

    private var countList=ArrayList<String>()
    private var resultCountList=ArrayList<CountryListDataClass>()
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        binding = ActivityCountryChoiceBinding.inflate(layoutInflater); // 1
        setContentView(binding.root); //
        val isoCodes: Array<String> = Locale.getISOCountries()
        for (i in isoCodes.indices) {
            val locale = Locale("", isoCodes[i])
            Log.d("helloworld",isoCodes[i])
        }
        setRecyclerView()
        setListener()
        setCountList()

    }

    private fun setRecyclerView(){
        binding.countryChoiceRvResult.adapter=CountryListRvAdapter(resultCountList)
        binding.countryChoiceRvResult.layoutManager=LinearLayoutManager(this,LinearLayoutManager.VERTICAL,false)
    }

    private fun setListener(){
        binding.countryChoiceImgBack.setOnClickListener {
            finish()
        }

        binding.countryChoiceEditSearch.addTextChangedListener {
            resultCountList.clear()
            if(!it.isNullOrEmpty()){
                for(i in 0 until countList.size){
                    if(countList[i].contains(it.toString())){
                        resultCountList.add(CountryListDataClass(countList[i]))
                    }
                }
            }
            (binding.countryChoiceRvResult.adapter as CountryListRvAdapter).notifyDataSetChanged()
        }

        (binding.countryChoiceRvResult.adapter as CountryListRvAdapter).setOnCountryClickListener(object:CountryListRvAdapter.OnCountryClickListener{
            override fun onItemClick(country: String?) {
                var intent= Intent(this@CountryChoiceActivity,DateChoiceActivity::class.java)
                intent.putExtra("country",country)
                startActivity(intent)
            }

        })


    }



    private fun setCountList(){
        countList.add("가나")
        countList.add("가봉")
        countList.add("가이아나")
        countList.add("감비아")
        countList.add("건지 섬")
        countList.add("과들루프")
        countList.add("과테말라")
        countList.add("괌")
        countList.add("그레나다")
        countList.add("그리스")
        countList.add("그린란드")
        countList.add("기니")
        countList.add("기니비사우")
        countList.add("나미비아")
        countList.add("나우루")
        countList.add("나이지리아")
        countList.add("남극")
        countList.add("남수단")
        countList.add("남아프리카 공화국")
        countList.add("네덜란드")
        countList.add("네덜란드령 안틸레스")
        countList.add("네팔")
        countList.add("노르웨이")
        countList.add("노퍽 섬")
        countList.add("누벨칼레도니")
        countList.add("뉴질랜드")
        countList.add("니우에")
        countList.add("니제르")
        countList.add("니카라과")
        countList.add("대한민국")
        countList.add("덴마크")
        countList.add("도미니카 공화국")
        countList.add("도미니카 연방")
        countList.add("독일")
        countList.add("동티모르")
        countList.add("라오스")
        countList.add("라이베리아")
        countList.add("라트비아")
        countList.add("러시아")
        countList.add("레바논")
        countList.add("레소토")
        countList.add("레위니옹")
        countList.add("루마니아")
        countList.add("룩셈부르크")
        countList.add("르완다")
        countList.add("리비아")
        countList.add("리투아니아")
        countList.add("리히텐슈타인")
        countList.add("마다가스카르")
        countList.add("마르티니크")
        countList.add("마셜 제도")
        countList.add("마요트")
        countList.add("마카오")
        countList.add("마케도니아 공화국")
        countList.add("말라위")
        countList.add("말레이시아")
        countList.add("말리")
        countList.add("맨 섬")
        countList.add("멕시코")
        countList.add("모나코")
        countList.add("모로코")
        countList.add("모리셔스")
        countList.add("모리타니")
        countList.add("모잠비크")
        countList.add("몬테네그로")
        countList.add("몬트세랫")
        countList.add("몰도바")
        countList.add("몰디브")
        countList.add("몰타")
        countList.add("몽골")
        countList.add("미국")
        countList.add("미국령 군소 제도")
        countList.add("미국령 버진아일랜드")
        countList.add("미얀마")
        countList.add("미크로네시아 연방")
        countList.add("바누아투")
        countList.add("바레인")
        countList.add("바베이도스")
        countList.add("바티칸 시국")
        countList.add("바하마")
        countList.add("방글라데시")
        countList.add("버뮤다")
        countList.add("베냉")
        countList.add("베네수엘라")
        countList.add("베트남")
        countList.add("벨기에")
        countList.add("벨라루스")
        countList.add("벨리즈")
        countList.add("보스니아 헤르체고비나")
        countList.add("보츠와나")
        countList.add("볼리비아")
        countList.add("부룬디")
        countList.add("부르키나파소")
        countList.add("부베 섬")
        countList.add("부탄")
        countList.add("북마리아나 제도")
        countList.add("불가리아")
        countList.add("브라질")
        countList.add("브루나이")
        countList.add("사모아")
        countList.add("사우디아라비아")
        countList.add("사우스조지아 사우스샌드위치 제도")
        countList.add("산마리노")
        countList.add("상투메 프린시페")
        countList.add("생피에르 미클롱")
        countList.add("서사하라")
        countList.add("세네갈")
        countList.add("세르비아")
        countList.add("세이셸")
        countList.add("세인트루시아")
        countList.add("세인트빈센트 그레나딘")
        countList.add("세인트키츠 네비스")
        countList.add("세인트헬레나")
        countList.add("소말리아")
        countList.add("솔로몬 제도")
        countList.add("수단")
        countList.add("수리남")
        countList.add("스리랑카")
        countList.add("스발바르 얀마옌")
        countList.add("스와질란드")
        countList.add("스웨덴")
        countList.add("스위스")
        countList.add("스페인")
        countList.add("슬로바키아")
        countList.add("슬로베니아")
        countList.add("시리아")
        countList.add("시에라리온")
        countList.add("싱가포르")
        countList.add("아랍에미리트")
        countList.add("아루바")
        countList.add("아르메니아")
        countList.add("아르헨티나")
        countList.add("아메리칸사모아")
        countList.add("아이슬란드")
        countList.add("아이티")
        countList.add("아일랜드")
        countList.add("아제르바이잔")
        countList.add("아프가니스탄")
        countList.add("안도라")
        countList.add("알바니아")
        countList.add("알제리")
        countList.add("앙골라")
        countList.add("앤티가 바부다")
        countList.add("앵귈라")
        countList.add("에리트레아")
        countList.add("에스토니아")
        countList.add("에콰도르")
        countList.add("에티오피아")
        countList.add("엘살바도르")
        countList.add("영국영국")
        countList.add("영국령 버진아일랜드")
        countList.add("영국령 인도양 지역")
        countList.add("예멘")
        countList.add("오만")
        countList.add("오스트레일리아")
        countList.add("오스트리아")
        countList.add("온두라스")
        countList.add("올란드 제도")
        countList.add("왈리스 퓌튀나")
        countList.add("요르단")
        countList.add("우간다")
        countList.add("우루과이")
        countList.add("우즈베키스탄")
        countList.add("우크라이나")
        countList.add("이라크")
        countList.add("이란")
        countList.add("이스라엘")
        countList.add("이집트")
        countList.add("이탈리아")
        countList.add("인도")
        countList.add("인도네시아")
        countList.add("일본")
        countList.add("자메이카")
        countList.add("잠비아")
        countList.add("저지 섬")
        countList.add("적도 기니")
        countList.add("조선민주주의인민공화국")
        countList.add("조지아")
        countList.add("중앙아프리카 공화국")
        countList.add("중화민국")
        countList.add("중화인민공화국")
        countList.add("지부티")
        countList.add("지브롤터")
        countList.add("짐바브웨")
        countList.add("차드")
        countList.add("체코")
        countList.add("칠레")
        countList.add("카메룬")
        countList.add("카보베르데")
        countList.add("카자흐스탄")
        countList.add("카타르")
        countList.add("캄보디아")
        countList.add("캐나다")
        countList.add("케냐")
        countList.add("케이맨 제도")
        countList.add("코모로")
        countList.add("코스타리카")
        countList.add("코코스 제도")
        countList.add("코트디부아르")
        countList.add("콜롬비아")
        countList.add("콩고 공화국")
        countList.add("콩고 민주 공화국")
        countList.add("쿠바")
        countList.add("쿠웨이트")
        countList.add("쿡 제도")
        countList.add("크로아티아")
        countList.add("크리스마스 섬")
        countList.add("키르기스스탄")
        countList.add("키리바시")
        countList.add("키프로스")
        countList.add("타이")
        countList.add("타지키스탄")
        countList.add("탄자니아")
        countList.add("터크스 케이커스 제도")
        countList.add("터키")
        countList.add("토고")
        countList.add("토켈라우")
        countList.add("통가")
        countList.add("투르크메니스탄")
        countList.add("투발루")
        countList.add("튀니지")
        countList.add("트리니다드 토바고")
        countList.add("파나마")
        countList.add("파라과이")
        countList.add("파키스탄")
        countList.add("파푸아 뉴기니")
        countList.add("팔라우")
        countList.add("팔레스타인")
        countList.add("페로 제도")
        countList.add("페루")
        countList.add("포르투갈")
        countList.add("포클랜드 제도")
        countList.add("폴란드")
        countList.add("푸에르토리코")
        countList.add("프랑스")
        countList.add("프랑스령 기아나")
        countList.add("프랑스령 남부와 남극 지역")
        countList.add("프랑스령 폴리네시아")
        countList.add("피지")
        countList.add("핀란드")
        countList.add("필리핀")
        countList.add("핏케언 제도")
        countList.add("허드 맥도널드 제도")
        countList.add("헝가리")
        countList.add("홍콩")

        for(i in 0 until countList.size){
            resultCountList.add(CountryListDataClass(countList[i]))
        }

    }
}